// <copyright file="PostOpportunityCreate.cs" company="">
// Copyright (c) 2015 All Rights Reserved
// </copyright>
// <author></author>
// <date>9/22/2015 12:11:16 PM</date>
// <summary>Implements the PostOpportunityCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>
namespace DynamicCRMWithNexmoSMS.Plugins
{
    using System;
    using System.ServiceModel;
    using Microsoft.Xrm.Sdk;
    using Microsoft.Xrm.Sdk.Query;
    using System.Xml;
    using System.IO;
    using System.Web;

    /// <summary>
    /// PostOpportunityCreate Plugin.
    /// </summary>    
    public class PostOpportunityCreate: Plugin
    {

        private string NexmoApiKey = string.Empty; 
        private string NexmoApiSecret = string.Empty;
        //private string FromUser = string.Empty;
        private Double  Threshold;
        private string EnableSMS = string.Empty; 
        /// <summary>
        /// Alias of the image registered for the snapshot of the 
        /// primary entity's attributes after the core platform operation executes.
        /// The image contains the following attributes:
        /// No Attributes
        /// 
        /// Note: Only synchronous post-event and asynchronous registered plug-ins 
        /// have PostEntityImages populated.
        /// </summary>
        private readonly string postImageAlias = "PostImage";

        /// <summary>
        /// Initializes a new instance of the <see cref="PostOpportunityCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecure) configuration information.</param>
        /// <param name="secure">Contains non-public (secure) configuration information. 
        /// When using Microsoft Dynamics CRM for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PostOpportunityCreate(string unsecure, string secure)
            : base(typeof(PostOpportunityCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Create", "opportunity", new Action<LocalPluginContext>(ExecutePostOpportunityCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.

            try
            {
                // TODO: Implement your custom configuration handling.
                using (XmlReader reader = XmlReader.Create(new StringReader(unsecure)))
                {
                    // Load fields from settings
                    reader.MoveToContent();

                    reader.MoveToAttribute("APIKey");
                    NexmoApiKey = Convert.ToString(reader.GetAttribute("APIKey"));

                    reader.MoveToAttribute("APISecret");
                    NexmoApiSecret = Convert.ToString(reader.GetAttribute("APISecret"));

                    //reader.MoveToAttribute("FromUser");
                    //FromUser = Convert.ToString(reader.GetAttribute("FromUser"));

                    reader.MoveToAttribute("EnableNexmoSMS");
                    EnableSMS = Convert.ToString(reader.GetAttribute("EnableNexmoSMS"));

                    reader.MoveToAttribute("Threshold");
                    if(!string.IsNullOrEmpty(reader.GetAttribute("Threshold")))
                       Threshold = Convert.ToDouble(reader.GetAttribute("Threshold"));

                  
                }
            }
            catch(Exception ex) 
            {
                throw new InvalidPluginExecutionException(string.Format("An error occured in ExecutePostOpportunityCreate plugin: {0} {1} {2}", ex.ToString(), ex.InnerException, ex.StackTrace));
            }




        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PostOpportunityCreate"/> class.
        /// </summary>
        public PostOpportunityCreate()
            : base(typeof(PostOpportunityCreate))
        {
            base.RegisteredEvents.Add(new Tuple<int, string, string, Action<LocalPluginContext>>(40, "Create", "opportunity", new Action<LocalPluginContext>(ExecutePostOpportunityCreate)));

            // Note : you can register for more events here if this plugin is not specific to an individual entity and message combination.
            // You may also need to update your RegisterFile.crmregister plug-in registration file to reflect any change.
        }

        /// <summary>
        /// Executes the plug-in.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics CRM caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected void ExecutePostOpportunityCreate(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new ArgumentNullException("localContext");
            }

            try
            {
            IPluginExecutionContext context = localContext.PluginExecutionContext;

            Entity postImageEntity = (context.PostEntityImages != null && context.PostEntityImages.Contains(this.postImageAlias)) ? context.PostEntityImages[this.postImageAlias] : null;

            if (EnableSMS == "false")
                return; 

                if (context.InputParameters.Contains("Target") &&
                context.InputParameters["Target"] is Entity)
                {

                    SmsSender s = new SmsSender();
                    //Organization Service
                    IOrganizationService service = localContext.OrganizationService;

                    //Tracing Service
                    ITracingService trace = (ITracingService)localContext.TracingService;

                    trace.Trace("Nemxo API Key " + NexmoApiKey);
                    trace.Trace("Nemxo API secret " + NexmoApiSecret);
                    //trace.Trace("Nemxo from User " + FromUser);
                    trace.Trace("Threshold " + Threshold.ToString());

                     string UserNumber =  s.GetAccountNumber(NexmoApiKey, NexmoApiSecret);
                     trace.Trace("UserNumber" + UserNumber.ToString());

                    string oppsCreatedByID = string.Empty;
                    string OppsCreatedBy = string.Empty;
                    string OppsBugestAmount = string.Empty;
                    string OppsAccountName = string.Empty;
                    string OppsBugestAmountValue = string.Empty; 
                    string OppCurrency = string.Empty;
                    string OppCurrencySymbol = string.Empty; 
                    string OppTitle = string.Empty;
                    string message = "A new opportunity '{0}' for {1} with probable value {2} has been added.";

                    OppTitle = postImageEntity.Attributes["name"].ToString();

//                    string fetchxmlOpp = @"<fetch mapping='logical'> 
//                                          <entity name='opportunity'><all-attributes/>
//                                          <filter type='and'>
//                                          <condition attribute='opportunityid' operator='eq' uitype='opportunity' uiname='" + OppTitle + "' value='{" + postImageEntity.Id.ToString() + "}' />" +
//                                         "</filter></entity></fetch>";

                    trace.Trace("Opp ID: " + postImageEntity.Id.ToString());

                    Entity CreatedOpp = service.Retrieve("opportunity", new Guid(postImageEntity.Id.ToString()), new ColumnSet(true));
                    //Entity CreatedOpp = CurrentOpp.Entities[0];

                    if (CreatedOpp.Attributes.Contains("customerid"))
                    {
                        trace.Trace("customerid found");
                        trace.Trace("customerid:" + CreatedOpp.Attributes["customerid"]);
                        string accountID =  ((Microsoft.Xrm.Sdk.EntityReference)(CreatedOpp.Attributes["customerid"])).Id.ToString();
                        string fetchxmlAccount = @"<fetch mapping='logical'> 
                                          <entity name='account'><all-attributes/>
                                          <filter type='and'>
                                          <condition attribute='accountid' operator='eq' uitype='account'  value='{" + accountID + "}' />" +
                                         "</filter></entity></fetch>";

                        EntityCollection AccountDetails = service.RetrieveMultiple(new FetchExpression(fetchxmlAccount));
                        if (AccountDetails != null)
                        {
                            if (AccountDetails.Entities.Count > 0)
                            {
                                trace.Trace("account found");
                                OppsAccountName = AccountDetails.Entities[0].Attributes["name"].ToString();
                                
                            }
                            else
                            {
                                trace.Trace("AccountDetails rows count equals 0");
                            }
                        }
                        else
                        {
                            trace.Trace("AccountDetails is null");
                        }
                    }
                    else
                    {
                        trace.Trace("customerid not found");
                    }
                    trace.Trace("OppsAccountName" + OppsAccountName);

                    OppTitle = CreatedOpp.Attributes["name"].ToString();
                    trace.Trace("OppTitle: " + OppTitle);
                    if (CreatedOpp.Attributes.Contains("budgetamount"))
                    {
                        OppsBugestAmount = ((Microsoft.Xrm.Sdk.Money)CreatedOpp.Attributes["budgetamount"]).Value.ToString();
                        OppCurrency = ((Microsoft.Xrm.Sdk.EntityReference)(CreatedOpp.Attributes["transactioncurrencyid"])).Id.ToString();
                        OppsBugestAmount = Convert.ToDouble(OppsBugestAmount).ToString("0.00"); 
                        //get CurrecySymbol 
                        Entity Currency = service.Retrieve("transactioncurrency", new Guid(OppCurrency), new ColumnSet(true));
                        string currencySymbol = Currency.Attributes["currencysymbol"].ToString();
                        OppsBugestAmountValue = OppsBugestAmount;
                        OppsBugestAmount = currencySymbol + OppsBugestAmount; 
                        trace.Trace("OppsBugestAmount: " + OppsBugestAmount);
                    }

                    OppsCreatedBy = ((Microsoft.Xrm.Sdk.EntityReference)(CreatedOpp.Attributes["createdby"])).Name.ToString();
                    trace.Trace("OppsCreatedBy: " + OppsCreatedBy);
                    oppsCreatedByID = ((Microsoft.Xrm.Sdk.EntityReference)(CreatedOpp.Attributes["createdby"])).Id.ToString();
                    trace.Trace("oppsCreatedByID: " + oppsCreatedByID);
                    //OppsAccountName = ((Microsoft.Xrm.Sdk.EntityReference)(CreatedOpp.Attributes["customerid"])).Name.ToString();
                    //trace.Trace("customerid: " + OppsAccountName);
                  
                    string fetchxmluser = @"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>" +
                     "<entity name='systemuser'>" +
                     "<attribute name='fullname' />" +
                    "<attribute name='businessunitid' />" +
                    "<attribute name='title' /> " +
                    "<attribute name='address1_telephone1'/>" +
                    "<attribute name='positionid' /> " +
                    "<attribute name='systemuserid' /> " +
                    "<attribute name='mobilephone' />" +
                    "<attribute name='parentsystemuserid' />" +
                    "<attribute name='firstname' />" +
                    "<order attribute='fullname' descending= 'false' />" +
                    "</entity>" +
                     "</fetch>";

                    EntityCollection entitiesUsers = service.RetrieveMultiple(new FetchExpression(fetchxmluser));
                    trace.Trace("entitiesUsers: " + entitiesUsers.Entities.Count);
                    Entity e = null;
                    Entity eManager = null;
                    string managerUID = string.Empty;

                    //Get manager ID for current user 
                    for (int count = 0; count < entitiesUsers.Entities.Count; count++)
                    {
                        e = null;
                        e = entitiesUsers.Entities[count];
                        if (e.Id.ToString() == oppsCreatedByID && e.Attributes.Contains("parentsystemuserid"))
                        {
                            managerUID = ((Microsoft.Xrm.Sdk.EntityReference)(e.Attributes["parentsystemuserid"])).Id.ToString();
                            break;
                        }
                    }
                    trace.Trace("managerUID: " + managerUID);
                    //Get Manager Entity 
                    if (!string.IsNullOrEmpty(managerUID))
                    {
                        for (int count = 0; count < entitiesUsers.Entities.Count; count++)
                        {
                            eManager = null;
                            if (entitiesUsers.Entities[count].Id.ToString() == managerUID)
                            {
                                eManager = entitiesUsers.Entities[count];
                                break;
                            }
                        }


                       //Get Manager Phone number 
                        string ToNumber = string.Empty;
                        string smsMessage = string.Empty;
                        if (eManager != null)
                        {
                            trace.Trace("Manager Name: " + eManager.Attributes["fullname"].ToString());
                            if (eManager.Attributes.Contains("mobilephone"))
                            {
                                ToNumber = eManager.Attributes["mobilephone"].ToString();
                                trace.Trace("ToNumber: " + ToNumber);
                                if(string.IsNullOrEmpty(OppsAccountName))
                                {
                                   
                                    message = "A new opportunity '{0}' with probable value {1} has been added.";
                                    smsMessage = string.Format(message, OppTitle, OppsBugestAmount);
                                }
                                else 
                                {
                                    message = "A new opportunity '{0}' for {1} with probable value {2} has been added.";
                                    smsMessage = string.Format(message, OppTitle, OppsAccountName, OppsBugestAmount);
                                }
                                
                               
                            }
                        }

                     

                        //update the message detail 
                        if (!string.IsNullOrEmpty(OppsBugestAmountValue) && !string.IsNullOrEmpty(ToNumber))
                        {
                            if (Convert.ToDouble(OppsBugestAmountValue) > Threshold)
                            {
                                smsMessage = HTMLEncodeSpecialChars (smsMessage);
                                s.SendSMS(ToNumber, UserNumber, NexmoApiKey, NexmoApiSecret, Uri.EscapeDataString(smsMessage));
                                //throw new InvalidPluginExecutionException(string.Format("SMS send message {0}", smsMessage));
                            }
                            else
                            {
                                //throw new InvalidPluginExecutionException(string.Format("SMS Will not send message {0}", smsMessage));
                            }

                        }
                    }
                    //throw new InvalidPluginExecutionException(string.Format("updated message {0}", smsMessage));
                }
            }
            catch (Exception ex)
            {
                throw new InvalidPluginExecutionException(string.Format("An error occured in ExecutePostOpportunityCreate plugin: {0} {1} {2}", ex.ToString(), ex.InnerException, ex.StackTrace));
            }

           
        }


        public string HTMLEncodeSpecialChars(string text)
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            foreach (char c in text)
            {
                if (c > 127) // special chars
                    sb.Append(String.Format("&#{0};", (int)c));
                else
                    sb.Append(c);
            }
            return sb.ToString();
        }
    }
}
